title: Abdelrahman Ahmed
author: Abdelrahman Ahmed
email: ab@abahmed.com
description: "Software Engineer & Open Source Enthusiast"
keywords: software engineer open source enthusiast blog techincal development
sass:
  sass_dir: _sass
  # generate social links in footer
disqus_shortname: abahmed-com
social_links:
  twitter: abahmed23
  github:  abahmed
  linkedIn: abahmed12
  email: ab@abahmed.com

twitter:
  username: abahmed23
  card: summary

featured_posts:
  - 080f2106-f03d-4941-9555-547e4378ef33

plugins:
  - jemoji
  - jekyll-seo-tag
